export const ActionTypes = {
  SET_PRODCUTS: "SET_PRODCUTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  INCREMENT_PRODUCT: "INCREMENT_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
};

